project:
  type: website
  output-dir: docs

website:
  title: "AI Project Club"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journa
    css: styles.css
    toc: true

# cerulean