project:
  type: website
  output-dir: docs

website:
  title: "AI Project Club"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://forms.gle/2mffx9cai6ohkN8p8
        text: Register

format:
  html:
    theme: journal
    css: styles.css
    toc: true

# cerulean